apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-webhook
  namespace: image-processing
  labels:
    app: image-webhook
    app.kubernetes.io/part-of: image-processing-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-webhook
  template:
    metadata:
      labels:
        app: image-webhook
    spec:
      containers:
      - name: webhook
        image: docker.io/davidandw190/image-processing-webhook:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: SOURCE_ID
          value: "image-processing/webhook"
        - name: EVENT_TYPE
          value: "image.storage.requested"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: image-webhook
  namespace: image-processing
  labels:
    app: image-webhook
    app.kubernetes.io/part-of: image-processing-system
spec:
  selector:
    app: image-webhook
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
