apiVersion: v1
kind: Service
metadata:
  name: image-webhook-external
  namespace: image-processing
  labels:
    app: image-webhook
    app.kubernetes.io/part-of: image-processing-system
spec:
  type: NodePort
  selector:
    app: image-webhook
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30070
