apiVersion: v1
kind: ConfigMap
metadata:
  name: config-br-default
  namespace: image-processing
data:
  channelTemplateSpec: |
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: image-processing-broker
  namespace: image-processing
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-br-default
    namespace: image-processing
