apiVersion: v1
kind: Namespace
metadata:
  name: image-processing
  labels:
    name: image-processing
    environment: production
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: object-storage
