apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: image-processing-broker
  namespace: image-processing
  annotations:
    eventing.knative.dev/broker.class: RabbitMQ
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: broker-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
  namespace: image-processing
data:
  queueLength: "10000"
  deliveryTimeout: "300s"
  retryCount: "3"
