apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: image-processing-sink
  namespace: image-processing
spec:
  subject:
    apiVersion: v1
    kind: Service
    selector:
      matchLabels:
        app.kubernetes.io/component: image-processing
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: image-processing-broker
