apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: flux-system
  matchLabels:
    app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo:6.7.1
        imagepullpolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        resources:
          limits:
            memory: '64Mi'
            cpu: '250m'
          requests:
            memory: '32Mi'
            cpu: '100m'
        livenessProbe:
          httpGet:


