apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: image-processing-broker
  namespace: image-processing
  labels:
    app.kubernetes.io/name: image-processing-broker
    app.kubernetes.io/part-of: image-processing-system
