apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: downloader-trigger
  namespace: image-processing
  labels:
    app.kubernetes.io/name: downloader-trigger
    app.kubernetes.io/part-of: image-processing-system
spec:
  broker: image-processing-broker
  filter:
    attributes:
      type: image.upload.requested
      category: storage
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: downloader
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: processor-trigger
  namespace: image-processing
  labels:
    app.kubernetes.io/name: processor-trigger
    app.kubernetes.io/part-of: image-processing-system
spec:
  broker: image-processing-broker
  filter:
    attributes:
      type: image.storage.completed
      category: processing
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: error-trigger
  namespace: image-processing
  labels:
    app.kubernetes.io/name: error-trigger
    app.kubernetes.io/part-of: image-processing-system
spec:
  broker: image-processing-broker
  filter:
    attributes:
      type: image.error.storage, image.error.processing, image.error.validation
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: error-handler
