apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: storage-trigger
  namespace: image-processing
  labels:
    app.kubernetes.io/name: storage-trigger
    app.kubernetes.io/part-of: image-processing-system
spec:
  broker: image-processing-broker
  filter:
    attributes:
      type: image.storage.requested
      category: storage
      source: "image-processing/storage"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: downloader
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: processing-trigger
  namespace: image-processing
  labels:
    app.kubernetes.io/name: processing-trigger
    app.kubernetes.io/part-of: image-processing-system
spec:
  broker: image-processing-broker
  filter:
    attributes:
      type: image.storage.completed
      category: processing
      source: "image-processing/processor"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: error-trigger
  namespace: image-processing
  labels:
    app.kubernetes.io/name: error-trigger
    app.kubernetes.io/part-of: image-processing-system
spec:
  broker: image-processing-broker
  filter:
    attributes:
      type: image.error
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: error-handler
