apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: image-processing-sinkbinding
  namespace: image-processing
  labels:
    app.kubernetes.io/name: image-processing-sinkbinding
    app.kubernetes.io/part-of: image-processing-system
spec:
  subject:
    apiVersion: v1
    kind: Service
    selector:
      matchLabels:
        app.kubernetes.io/role: event-source
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: image-processing-broker
