apiVersion: v1
kind: ConfigMap
metadata:
  name: image-processing-config
  namespace: image-processing
  labels:
    app.kubernetes.io/name: image-processing-config
    app.kubernetes.io/part-of: image-processing-system
data:
  # event config
  EVENT_SOURCE: "image-processing-system"
  EVENT_SOURCE_STORAGE: "image-processing/storage"
  EVENT_SOURCE_PROCESSOR: "image-processing/processor"
  BROKER_URL: "http://broker-ingress.knative-eventing.svc.cluster.local/image-processing/image-processing-broker"

  # minio config
  MINIO_ENDPOINT: "minio.image-processing.svc.cluster.local:9000"
  RAW_BUCKET: "raw-images"
  PROCESSED_BUCKET: "processed-images"
  MINIO_SECURE: "false"

  # connection
  CONNECTION_TIMEOUT: "5"
  MAX_RETRIES: "3"

  # image processing
  JPEG_QUALITY: "85" # valid range: 1-100
  MAX_IMAGE_SIZE: "800"
  CONTRAST_ENHANCEMENT: "1.2" # valid range: 0.5-2.0
