bootstrap:
	flux bootstrap github \
		--token-auth=false \
		--owner=davidandw190 \
		--repository=k8s-lab \
		--branch=main \
		--path=clusters/podinfo \
		--read-write-key=true \
		--components-extra='image-reflector-controller,image-automation-controller' \
		--personal