apiVersion: v1
kind: Namespace
metadata:
  name: image-processing
  labels:
    app.kubernetes.io/name: image-processing
    app.kubernetes.io/instance: image-processing
    app.kubernetes.io/part-of: image-processing-system
    environment: production
  annotations:
    description: "Namespace for the image processing workflow including MinIO and Vault components"
