apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-scheduler
  namespace: custom-scheduler
  annotations:
    description: "Service account for the data locality aware scheduler"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: data-locality-scheduler-role
  annotations:
    description: "Role providing necessary permissions for the custom scheduler"
rules:
- apiGroups: [ "" ]
  resources: [ "endpoints" ]
  verbs: [ "get", "create", "update" ]
- apiGroups: [ "" ]
  resources: [ "nodes" ]
  verbs: [ "get", "list", "watch", "update", "patch" ]
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch", "update", "patch" ]
- apiGroups: [ "" ]
  resources: [ "bindings", "pods/binding" ]
  verbs: [ "create" ]
- apiGroups: [ "" ]
  resources: [ "pods/status" ]
  verbs: [ "update", "patch" ]
- apiGroups: [ "" ]
  resources: [ "events" ]
  verbs: [ "create", "patch", "update" ]
- apiGroups: [ "" ]
  resources: [ "persistentvolumes", "persistentvolumeclaims" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "" ]
  resources: [ "services" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "storage.k8s.io" ]
  resources: [ "storageclasses" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-locality-scheduler-binding
  annotations:
    description: "Binding that grants the scheduler service account the necessary permissions"
subjects:
- kind: ServiceAccount
  name: custom-scheduler
  namespace: custom-scheduler
roleRef:
  kind: ClusterRole
  name: data-locality-scheduler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-daemon
  namespace: custom-scheduler
  annotations:
    description: "Service account for the node capability daemon"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-capability-daemon-role
  annotations:
    description: "Role providing necessary permissions for the node daemon"
rules:
- apiGroups: [ "" ]
  resources: [ "nodes" ]
  verbs: [ "get", "list", "watch", "update", "patch" ]
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "" ]
  resources: [ "events" ]
  verbs: [ "create", "patch" ]
- apiGroups: [ "" ]
  resources: [ "persistentvolumes", "persistentvolumeclaims" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-capability-daemon-binding
  annotations:
    description: "Binding that grants the node daemon the necessary permissions"
subjects:
- kind: ServiceAccount
  name: node-daemon
  namespace: custom-scheduler
roleRef:
  kind: ClusterRole
  name: node-capability-daemon-role
  apiGroup: rbac.authorization.k8s.io
