apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-locality-scheduler
  namespace: custom-scheduler
  labels:
    app: data-locality-scheduler
  annotations:
    description: "Deployment for the data locality aware Kubernetes scheduler"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-locality-scheduler
  template:
    metadata:
      labels:
        app: data-locality-scheduler
    spec:
      serviceAccountName: custom-scheduler
      containers:
      - name: scheduler
        image: data-locality-scheduler:latest # TODO: replace with image reference in prod
        imagePullPolicy: IfNotPresent
        args:
        - "--scheduler-name=data-locality-scheduler"
        - "--enable-data-locality=true"
        - "--same-zone-bandwidth-mbps=500"
        - "--same-region-bandwidth-mbps=200"
        - "--edge-cloud-bandwidth-mbps=25"
        - "--v=2"
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: data-locality-scheduler
  namespace: custom-scheduler
  annotations:
    description: "Service exposing health check and API endpoints for the scheduler"
spec:
  selector:
    app: data-locality-scheduler
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
