apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: custom-scheduler
  annotations:
    description: "Test pod that utilizes the data locality scheduler"
    data.scheduler.thesis/input-1: "eo-scenes/sample-scene.tif,104857600,10,4,geotiff"
    data.scheduler.thesis/output-1: "cog-data/processed-scene.tif,52428800,0,4,cog"
spec:
  schedulerName: data-locality-scheduler
  containers:
  - name: eo-processor
    image: python:3.9
    command: [ "sleep", "3600" ]
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
  restartPolicy: Never
