apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: custom-scheduler
  annotations:
    description: "Test pod that utilizes the custom scheduler for placement"
    scheduler.thesis/required-capability: "compute"
    scheduler.thesis/memory-intensive: "true"
spec:
  schedulerName: custom-scheduler
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  restartPolicy: Never
