apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: image-processing
  labels:
    app.kubernetes.io/name: minio-config
    app.kubernetes.io/instance: minio
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: image-processing-system
  annotations:
    description: "Configuration for MinIO settings"
data:
  MINIO_BROWSER_REDIRECT_URL: "http://localhost:9001"
  MINIO_PROMETHEUS_URL: "http://prometheus-server:9090"
  MINIO_PROMETHEUS_JOB_ID: "minio-job"
  MINIO_PROMETHEUS_AUTH_TYPE: "public"
  MINIO_API_REQUESTS_MAX: "1600"
  MINIO_BROWSER: "on"
  MINIO_COMPRESS: "on"
  MINIO_COMPRESS_EXTENSIONS: ".txt,.log,.csv,.json,.tar,.xml,.bin"
