apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: image-processing
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
    app.kubernetes.io/component: object-storage
    app.kubernetes.io/part-of: image-processing-system
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
        app.kubernetes.io/name: minio
        app.kubernetes.io/instance: minio
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "minio-role"
        vault.hashicorp.com/agent-inject-secret-minio-config: "minio/data/data/config"
        vault.hashicorp.com/agent-inject-template-minio-config: |
          {{- with secret "minio/data/data/config" -}}
          export MINIO_ROOT_USER="{{ .Data.data.MINIO_ROOT_USER }}"
          export MINIO_ROOT_PASSWORD="{{ .Data.data.MINIO_ROOT_PASSWORD }}"
          {{- end -}}
        vault.hashicorp.com/address: "http://vault.image-processing.svc:8200"
    spec:
      serviceAccountName: minio-vault-auth
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - "/bin/sh"
        - "-c"
        args:
        - |
          echo "Waiting for Vault secrets..."
          while [ ! -f /vault/secrets/minio-config ]; do
            sleep 2
            echo "Waiting for secrets..."
          done
          source /vault/secrets/minio-config
          echo "Starting MinIO server..."
          exec minio server /data --console-address ":9001"
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 10
          periodSeconds: 60
          failureThreshold: 3
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app.kubernetes.io/name: minio-data
        app.kubernetes.io/instance: minio
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
