apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: storage-system
  annotations:
    description: 'Enables Vault to validate Kubernetes service account tokens'
    security-level: 'critical'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: minio-vault-auth
  namespace: minio-system
