apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: image-processing
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app: vault
  ports:
  - port: 8200
    targetPort: 8200
