apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: image-processing
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    app.kubernetes.io/component: vault
    app.kubernetes.io/part-of: image-processing-system
  annotations:
    description: "Service exposing Vault"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app: vault
  ports:
  - port: 8200
    targetPort: 8200
    name: vault
