apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: image-processing
  labels:
    app.kubernetes.io/name: vault-config
    app.kubernetes.io/instance: vault
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: image-processing-system
  annotations:
    description: "Vault policy configuration for MinIO access"
data:
  config.hcl: |
    path "minio/*" {
      capabilities = ["read", "list"]
    }
    path "sys/audit/*" {
      capabilities = ["read"]
    }
