apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: image-processing
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    app.kubernetes.io/component: vault
    app.kubernetes.io/part-of: image-processing-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
        app.kubernetes.io/name: vault
        app.kubernetes.io/instance: vault
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8200"
    spec:
      serviceAccountName: minio-vault-auth
      containers:
      - name: vault
        image: hashicorp/vault:1.18.4
        args:
        - "server"
        - "-dev"
        - "-dev-root-token-id=root"
        - "-dev-listen-address=0.0.0.0:8200"
        ports:
        - containerPort: 8200
          name: vault
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "root"
        - name: VAULT_ADDR
          value: "http://localhost:8200"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        securityContext:
          capabilities:
            add: [ "IPC_LOCK" ]
        livenessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 10
          periodSeconds: 15
