apiVersion: v1
kind: Namespace
metadata:
  name: image-processing
  labels:
    name: image-processing
    environment: production
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: object-storage
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: minio-quota
  namespace: image-processing
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    requests.storage: 10Gi
