apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: image-processing
  labels:
    app.kubernetes.io/name: minio
type: Opaque
data:
  root-user: bWluaW9hZG1pbg==
  root-password: bWluaW9hZG1pbg==
