apiVersion: v1
kind: Namespace
metadata:
  name: minio-system
  labels:
    name: minio-system
    environment: production
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: object-storage
    app.kubernetes.io/part-of: storage-system
    app.kubernetes.io/managed-by: kubernetes
