apiVersion: v1
kind: Namespace
metadata:
  name: minio-system
  labels:
    name: minio-system
    environment: production
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: object-storage
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: minio-quota
  namespace: minio-system
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    requests.storage: 4Gi
