apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: minio-system
  labels:
    app.kubernetes.io/name: minio
type: Opaque
data:
  root-user: bWluaW8tYWRtaW4=
  root-password: bWluaW8tcGFzc3dvcmQtMTIz
