apiVersion: v1
kind: ResourceQuota
metadata:
  name: minio-quota
  namespace: minio-system
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    requests.storage: 10Gi
