apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: minio-system
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: credentials
type: Opaque
data:
  root-user: bWluaW8tYWRtaW4=
  root-password: bWluaW8tcGFzc3dvcmQtMTIz
  # for bucket encryption
  encryption-key: bWluaW8tZW5jcnlwdGlvbi1rZXktMTIzNDU=
