apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio-system
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "minio-role"
        vault.hashicorp.com/agent-inject-secret-minio-config: "minio/data/data/config"
        vault.hashicorp.com/agent-inject-template-minio-config: |
          {{- with secret "minio/data/data/config" -}}
          export MINIO_ROOT_USER="{{ .Data.data.MINIO_ROOT_USER }}"
          export MINIO_ROOT_PASSWORD="{{ .Data.data.MINIO_ROOT_PASSWORD }}"
          {{- end -}}
    spec:
      serviceAccountName: minio-vault-auth
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - "/bin/sh"
        - "-c"
        args:
        - |
          echo "Waiting for Vault secrets..."
          while [ ! -f /vault/secrets/minio-config ]; do
            sleep 2
            echo "Waiting for secrets..."
          done
          source /vault/secrets/minio-config
          echo "Starting MinIO server..."
          exec minio server /data --console-address ":9001"
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
