apiVersion: batch/v1
kind: Job
metadata:
  name: minio-test
  namespace: minio-system
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: test
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc:latest
        command:
        - /bin/sh
        - -c
        args:
        - |
          # Waiting for MinIO to be ready
          sleep 10

          # Configuring MinIO client
          mc alias set myminio http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"

          # Creating test bucket
          mc mb myminio/test-bucket

          # Creating test files
          echo "Hello MinIO" > /tmp/hello.txt
          dd if=/dev/urandom of=/tmp/test.bin bs=100K count=1

          # Uploading files
          mc cp /tmp/hello.txt myminio/test-bucket/
          mc cp /tmp/test.bin myminio/test-bucket/

          # Listing contents
          mc ls myminio/test-bucket/

          # Testing object tagging
          mc tag set myminio/test-bucket/hello.txt "content=text"

          # Verifying upload
          mc stat myminio/test-bucket/hello.txt
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: root-password
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      restartPolicy: Never
  backoffLimit: 3
