apiVersion: batch/v1
kind: Job
metadata:
  name: minio-test
  namespace: minio-system
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "minio-role"
        vault.hashicorp.com/agent-inject-secret-minio-config: "minio/data/data/config"
        vault.hashicorp.com/agent-inject-template-minio-config: |
          {{- with secret "minio/data/data/config" -}}
          export MINIO_ROOT_USER="{{ .Data.data.MINIO_ROOT_USER }}"
          export MINIO_ROOT_PASSWORD="{{ .Data.data.MINIO_ROOT_PASSWORD }}"
          {{- end -}}
    spec:
      serviceAccountName: minio-vault-auth
      containers:
      - name: mc
        image: minio/mc:latest
        command:
        - "/bin/sh"
        - "-c"
        args:
        - |
          echo "Starting MinIO test process..."
          echo "Waiting for Vault secrets to be injected..."
          timeout=60
          count=0
          while [ ! -f /vault/secrets/minio-config ]; do
            sleep 2
            count=$((count + 2))
            echo "Waiting for secrets... ($count seconds)"
            if [ $count -ge $timeout ]; then
              echo "Timeout waiting for secrets"
              exit 1
            fi
          done
          echo "MinIO credentials obtained, proceeding with tests..."
          source /vault/secrets/minio-config
          mc alias set myminio http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"
          echo "Creating test bucket..."
          mc mb myminio/test-bucket
          echo "Testing MinIO operations..."
          echo "Hello MinIO" > /tmp/hello.txt
          mc cp /tmp/hello.txt myminio/test-bucket/
          echo "Verifying upload..."
          mc ls myminio/test-bucket/
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      restartPolicy: Never
  backoffLimit: 3
